newrelic/newrelic-infra-operator

internal/mutator/pod/agent/agent_config.go
internal/mutator/pod/agent/injector.go
internal/mutator/pod/agent/injector_test.go
internal/operator/operator.go

internal/mutator/pod/agent: improve label hashing

---

.golangci.yml
Makefile
internal/mutator/pod/agent/injector.go

See commit messages for more details.

Re-enable scopelint linter

---

charts/newrelic-infra-operator/.helmignore
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/README.md
charts/newrelic-infra-operator/ci/test-values.yaml
charts/newrelic-infra-operator/templates/NOTES.txt
charts/newrelic-infra-operator/templates/_helpers.tpl
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/README.md
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/clusterrole.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/psp.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/role.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/rolebinding.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/serviceaccount.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/newrelic-infra-operator/templates/cert-manager.yaml
charts/newrelic-infra-operator/templates/clusterrole.yaml
charts/newrelic-infra-operator/templates/clusterrolebinding.yaml
charts/newrelic-infra-operator/templates/configmap.yaml
charts/newrelic-infra-operator/templates/deployment.yaml
charts/newrelic-infra-operator/templates/secret.yaml
charts/newrelic-infra-operator/templates/service.yaml
charts/newrelic-infra-operator/templates/serviceaccount.yaml
charts/newrelic-infra-operator/values.yaml

Moving chart from helm-chart-repository

chore(chart): move chart to new repository

---

.github/ct.yaml
.github/workflows/ci.yaml
.gitignore
charts/newrelic-infra-operator/Chart.lock
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/templates/NOTES.txt
charts/newrelic-infra-operator/templates/_helpers.tpl
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/clusterrole.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/job-createSecret.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/psp.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/role.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/rolebinding.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/serviceaccount.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/mutatingWebhookConfiguration.yaml
charts/newrelic-infra-operator/templates/cert-manager.yaml
charts/newrelic-infra-operator/templates/clusterrole.yaml
charts/newrelic-infra-operator/templates/clusterrolebinding.yaml
charts/newrelic-infra-operator/templates/configmap.yaml
charts/newrelic-infra-operator/templates/deployment.yaml
charts/newrelic-infra-operator/templates/secret.yaml
charts/newrelic-infra-operator/templates/service.yaml
charts/newrelic-infra-operator/templates/serviceaccount.yaml

This PR addresses https://github.com/newrelic/newrelic-infra-operator/issues/144

Adapt helm chart to common library

---

.github/workflows/release-chart.yml
charts/newrelic-infra-operator/Chart.lock
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/templates/_helpers.tpl
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/psp.yaml
charts/newrelic-infra-operator/templates/clusterrole.yaml
charts/newrelic-infra-operator/templates/configmap.yaml
charts/newrelic-infra-operator/templates/deployment.yaml
charts/newrelic-infra-operator/templates/serviceaccount.yaml

This continues the work done on https://github.com/newrelic/newrelic-infra-operator/pull/160 moving the helm chart to use common library

Adapt helm chart to common library - stage 2

---

.gitignore
README.md
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/README.md
charts/newrelic-infra-operator/README.md.gotmpl
charts/newrelic-infra-operator/templates/deployment.yaml
charts/newrelic-infra-operator/values.yaml

Document `values.yaml` and create a `README.md.gotmpl` to automate the creation and update of the README.

values.yaml documentation

---

charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/README.md

Relates to https://github.com/newrelic/helm-charts/issues/845.
Fix url to point to the proper branch.

Fix helm chart url

---

charts/newrelic-infra-operator/Chart.lock
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/README.md
charts/newrelic-infra-operator/README.md.gotmpl
charts/newrelic-infra-operator/values.yaml

Updating dependencies for common-library and injected container

chore(chart): updated dependencies

---

charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/values.yaml

updating image of the injected agent

chore(v2): chart update

---

.github/workflows/ci.yaml
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/README.md
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/clusterrole.yaml
charts/newrelic-infra-operator/templates/admission-webhooks/job-patch/psp.yaml
charts/newrelic-infra-operator/tests/job_patch_psp_test.yaml
charts/newrelic-infra-operator/values.yaml

Follow up of https://github.com/newrelic/newrelic-infra-operator/pull/226 as it was coming from a fork and I couldn't update it. It just updates the docs by running `helm-docs`.
cc @vuqtran88.

Disable PSPs by default

---

.github/workflows/security.yaml

Fixes https://github.com/newrelic/newrelic-infra-operator/issues/195

Enable Trivy scan

---

.github/renovate.json5

Signed-off-by: Hannah Troisi <htroisi@pixielabs.ai>

Update Renovate configs

---

.github/workflows/ci.yaml
charts/newrelic-infra-operator/Chart.yaml
charts/newrelic-infra-operator/tests/job_patch_psp_test.yaml
charts/newrelic-infra-operator/tests/job_serviceaccount_test.yaml
charts/newrelic-infra-operator/tests/rbac_test.yaml

Fixes https://github.com/newrelic/newrelic-infra-operator/actions/runs/4866896579/jobs/8678899228?pr=281
- Bump chart version so that [Run helm unit tests](https://github.com/newrelic/newrelic-infra-operator/blob/main/.github/workflows/ci.yaml#L35) github workflow step runs 
- Fix helm unit tests so that they pass
- Revert chart version bump

Fix helm unittest

---

charts/newrelic-infra-operator/Chart.yaml

This version is mainly for patches to fix vulnerabilities

Upgrade Chart Versions

---

CHANGELOG.md
charts/newrelic-infra-operator/templates/_helpers.tpl
charts/newrelic-infra-operator/values.yaml

Fixes bug reported in NR-153839
Please delete options that are not relevant.

bugfix: Address NR-153839 bug

---

.github/workflows/ci.yaml
CHANGELOG.md

Fix K8s Version Format
For example, "1.24.17" -> "v1.24.17"

Fix K8s Version Format

---

CHANGELOG.md

Please include a summary of the change in your pr and what it's fixing. 
Please delete options that are not relevant.

fix: Fix changelog

---

charts/newrelic-infra-operator/README.md

Please include a summary of the change in your pr and what it's fixing. 
Please delete options that are not relevant.

feat(docs): Update chart's README

---

charts/newrelic-infra-operator/Chart.yaml

Please include a summary of the change in your pr and what it's fixing. 
Please delete options that are not relevant.

feat(docs): Bump versions

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/changelog.yml
CHANGELOG.md

Update PR template to simplify usage

ci: Update pr template

---

.github/renovate.json5
.github/workflows/ci.yaml
.github/workflows/release-chart.yml
.github/workflows/release.yaml
.github/workflows/security.yaml
.github/workflows/trigger_prelease.yml
.gitignore
CHANGELOG.md
Makefile

Refactor workflows to automate agent release.

ci: Enable automatic release

---

Makefile

Update Makefile to allow for release automation.

ci: Update Makefile

---

.github/workflows/ci.yaml
CHANGELOG.md

chore: Remove 1.23 support

---

.github/workflows/ci.yaml
CHANGELOG.md

chore: Add k8s v1.28.0-rc.1 support

---

.github/workflows/ci.yaml

Disabling [semgrep action that has been deprecated](https://github.com/returntocorp/semgrep-action)

fix: Disable semgrep action that has been deprecated

---

.github/workflows/ci.yaml
CHANGELOG.md

chore: Replace k8s v1.28.0-rc.1 with k8s 1.28.3 support

---

.github/workflows/changelog.yml
.github/workflows/release-chart.yml
.github/workflows/release.yaml
.github/workflows/security.yaml
.github/workflows/trigger_prelease.yml
CHANGELOG.md

Update reusable workflow dependency

feat: Update reusable workflow dependency

---

.github/workflows/ci.yaml
CHANGELOG.md
Makefile
README.md

ci: add codecov

---

.github/workflows/ci.yaml

chore: update codecov config

---

.github/workflows/release.yaml

chore: Update secrets

---

.github/workflows/ci.yaml
.github/workflows/e2e.yaml
CHANGELOG.md
e2e/1_26-exceptions.yml
e2e/1_31-exceptions.yml

feat: Add Kube 1.31 support and drop 1.26

---

.github/workflows/ci.yaml
.github/workflows/e2e.yaml
CHANGELOG.md
e2e/1_27-exceptions.yml
e2e/1_32-exceptions.yml

Add support for v1.32.0 and drop v1.27.0.

Upgrade supported k8s version to 1.32.0 and drop 1.27.0

---

.github/workflows/changelog.yml
.github/workflows/ci.yaml
.github/workflows/e2e.yaml
.github/workflows/repolinter.yml
.github/workflows/trigger_release.yml

- update gha permissions to address a bunch of medium security warnings from github

chore: add gha permissions

---

.github/workflows/ci.yaml
.github/workflows/e2e.yaml
CHANGELOG.md
e2e/1_28-exceptions.yml
e2e/1_33-exceptions.yml

feat: add K8s v1.33 support remove v1.28 support
